kind: Deployment
apiVersion: apps/v1
metadata:
  name: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: zbio/todoapp:v2
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: mongo
